default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: assignment_development


test:
  <<: *default
  database:  assignment_test

#production:
  adapter: postgresql
  encoding: unicode
  database: assignment_production
  pool: 5
  username: root
  password: root